name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-angular.yml@master
        with:
            host: ta.bijanprogrammer.com
            base-href: /data-structures/
            project-name: data-structures
